### ISSUE TITLE
ERROR:  mail_style requires action_mailer (>= 1.2.3, runtime)

### ISSUE THREAD

**Issue by grimen** [purify/mail_style#1]
The previous gem name "actionmailer" in the Jeweler spec was replaced with "action_mailer", which is incorrect: Causing gem install error.

**Comment by grimen** [comment]
Problematic commit:

http://github.com/purify/mail_style/commit/343d650f5854b050204de36a19f90114949be597

**Comment by purify** [comment]
My bad.  Fixed now.
